//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingClientApplication.TimetablingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentlyLoggedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentlyLoggedIn {
            get {
                return this.CurrentlyLoggedInField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentlyLoggedInField, value) != true)) {
                    this.CurrentlyLoggedInField = value;
                    this.RaisePropertyChanged("CurrentlyLoggedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                if ((this.LastLoginField.Equals(value) != true)) {
                    this.LastLoginField = value;
                    this.RaisePropertyChanged("LastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserForename {
            get {
                return this.UserForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserForenameField, value) != true)) {
                    this.UserForenameField = value;
                    this.RaisePropertyChanged("UserForename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserTitle {
            get {
                return this.UserTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTitleField, value) != true)) {
                    this.UserTitleField = value;
                    this.RaisePropertyChanged("UserTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttendantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastDateEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LastUserEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RepeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNotes {
            get {
                return this.AdditionalNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalNotesField, value) != true)) {
                    this.AdditionalNotesField = value;
                    this.RaisePropertyChanged("AdditionalNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Attendants {
            get {
                return this.AttendantsField;
            }
            set {
                if ((this.AttendantsField.Equals(value) != true)) {
                    this.AttendantsField = value;
                    this.RaisePropertyChanged("Attendants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Course {
            get {
                return this.CourseField;
            }
            set {
                if ((this.CourseField.Equals(value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventDescription {
            get {
                return this.EventDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDescriptionField, value) != true)) {
                    this.EventDescriptionField = value;
                    this.RaisePropertyChanged("EventDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventTitle {
            get {
                return this.EventTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTitleField, value) != true)) {
                    this.EventTitleField = value;
                    this.RaisePropertyChanged("EventTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastDateEdited {
            get {
                return this.LastDateEditedField;
            }
            set {
                if ((this.LastDateEditedField.Equals(value) != true)) {
                    this.LastDateEditedField = value;
                    this.RaisePropertyChanged("LastDateEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LastUserEdited {
            get {
                return this.LastUserEditedField;
            }
            set {
                if ((this.LastUserEditedField.Equals(value) != true)) {
                    this.LastUserEditedField = value;
                    this.RaisePropertyChanged("LastUserEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Repeats {
            get {
                return this.RepeatsField;
            }
            set {
                if ((this.RepeatsField.Equals(value) != true)) {
                    this.RepeatsField = value;
                    this.RaisePropertyChanged("Repeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Room {
            get {
                return this.RoomField;
            }
            set {
                if ((this.RoomField.Equals(value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventType", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class EventType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEdited {
            get {
                return this.LastEditedField;
            }
            set {
                if ((this.LastEditedField.Equals(value) != true)) {
                    this.LastEditedField = value;
                    this.RaisePropertyChanged("LastEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeDescription {
            get {
                return this.TypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeDescriptionField, value) != true)) {
                    this.TypeDescriptionField = value;
                    this.RaisePropertyChanged("TypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class UserType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserTypeDescription {
            get {
                return this.UserTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeDescriptionField, value) != true)) {
                    this.UserTypeDescriptionField = value;
                    this.RaisePropertyChanged("UserTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserTypeId {
            get {
                return this.UserTypeIdField;
            }
            set {
                if ((this.UserTypeIdField.Equals(value) != true)) {
                    this.UserTypeIdField = value;
                    this.RaisePropertyChanged("UserTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomType", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class RoomType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomeTypeDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomTypeId {
            get {
                return this.RoomTypeIdField;
            }
            set {
                if ((this.RoomTypeIdField.Equals(value) != true)) {
                    this.RoomTypeIdField = value;
                    this.RaisePropertyChanged("RoomTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomeTypeDescription {
            get {
                return this.RoomeTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomeTypeDescriptionField, value) != true)) {
                    this.RoomeTypeDescriptionField = value;
                    this.RaisePropertyChanged("RoomeTypeDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuildingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildingId {
            get {
                return this.BuildingIdField;
            }
            set {
                if ((this.BuildingIdField.Equals(value) != true)) {
                    this.BuildingIdField = value;
                    this.RaisePropertyChanged("BuildingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((this.BuildingNumberField.Equals(value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDescription {
            get {
                return this.CourseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDescriptionField, value) != true)) {
                    this.CourseDescriptionField = value;
                    this.RaisePropertyChanged("CourseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Module : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastEdited {
            get {
                return this.LastEditedField;
            }
            set {
                if ((this.LastEditedField.Equals(value) != true)) {
                    this.LastEditedField = value;
                    this.RaisePropertyChanged("LastEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleDescription {
            get {
                return this.ModuleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleDescriptionField, value) != true)) {
                    this.ModuleDescriptionField = value;
                    this.RaisePropertyChanged("ModuleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId {
            get {
                return this.ModuleIdField;
            }
            set {
                if ((this.ModuleIdField.Equals(value) != true)) {
                    this.ModuleIdField = value;
                    this.RaisePropertyChanged("ModuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((this.BuildingField.Equals(value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomDescription {
            get {
                return this.RoomDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomDescriptionField, value) != true)) {
                    this.RoomDescriptionField = value;
                    this.RaisePropertyChanged("RoomDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((this.RoomTypeField.Equals(value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Time", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Time : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeLiteralField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeDescription {
            get {
                return this.TimeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeDescriptionField, value) != true)) {
                    this.TimeDescriptionField = value;
                    this.RaisePropertyChanged("TimeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeId {
            get {
                return this.TimeIdField;
            }
            set {
                if ((this.TimeIdField.Equals(value) != true)) {
                    this.TimeIdField = value;
                    this.RaisePropertyChanged("TimeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeLiteral {
            get {
                return this.TimeLiteralField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeLiteralField, value) != true)) {
                    this.TimeLiteralField = value;
                    this.RaisePropertyChanged("TimeLiteral");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepeatType", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class RepeatType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepeatDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RepeatTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepeatTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepeatDescription {
            get {
                return this.RepeatDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RepeatDescriptionField, value) != true)) {
                    this.RepeatDescriptionField = value;
                    this.RaisePropertyChanged("RepeatDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatTypeId {
            get {
                return this.RepeatTypeIdField;
            }
            set {
                if ((this.RepeatTypeIdField.Equals(value) != true)) {
                    this.RepeatTypeIdField = value;
                    this.RaisePropertyChanged("RepeatTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepeatTypeName {
            get {
                return this.RepeatTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RepeatTypeNameField, value) != true)) {
                    this.RepeatTypeNameField = value;
                    this.RaisePropertyChanged("RepeatTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimetablingService.ITimetablingService")]
    public interface ITimetablingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Check_Email_Not_Exist", ReplyAction="http://tempuri.org/ITimetablingService/Check_Email_Not_ExistResponse")]
        bool Check_Email_Not_Exist(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Check_Email_Not_Exist", ReplyAction="http://tempuri.org/ITimetablingService/Check_Email_Not_ExistResponse")]
        System.Threading.Tasks.Task<bool> Check_Email_Not_ExistAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Register_User", ReplyAction="http://tempuri.org/ITimetablingService/Register_UserResponse")]
        bool Register_User(TimetablingClientApplication.TimetablingService.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Register_User", ReplyAction="http://tempuri.org/ITimetablingService/Register_UserResponse")]
        System.Threading.Tasks.Task<bool> Register_UserAsync(TimetablingClientApplication.TimetablingService.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Login", ReplyAction="http://tempuri.org/ITimetablingService/LoginResponse")]
        int Login(string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/Login", ReplyAction="http://tempuri.org/ITimetablingService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateEvent", ReplyAction="http://tempuri.org/ITimetablingService/CreateEventResponse")]
        int CreateEvent(string eventTitle, int userId, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateEvent", ReplyAction="http://tempuri.org/ITimetablingService/CreateEventResponse")]
        System.Threading.Tasks.Task<int> CreateEventAsync(string eventTitle, int userId, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/EditEvent", ReplyAction="http://tempuri.org/ITimetablingService/EditEventResponse")]
        bool EditEvent(int editedEventId, int userId, string eventTitle, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/EditEvent", ReplyAction="http://tempuri.org/ITimetablingService/EditEventResponse")]
        System.Threading.Tasks.Task<bool> EditEventAsync(int editedEventId, int userId, string eventTitle, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/DeleteEvent", ReplyAction="http://tempuri.org/ITimetablingService/DeleteEventResponse")]
        bool DeleteEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/DeleteEvent", ReplyAction="http://tempuri.org/ITimetablingService/DeleteEventResponse")]
        System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnWeeksEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnWeeksEventsResponse")]
        TimetablingClientApplication.TimetablingService.Event[] ReturnWeeksEvents(System.DateTime weekBeginning, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnWeeksEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnWeeksEventsResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnWeeksEventsAsync(System.DateTime weekBeginning, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnEventsResponse")]
        TimetablingClientApplication.TimetablingService.Event[] ReturnEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnEventsResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnEventTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnEventTypesResponse")]
        TimetablingClientApplication.TimetablingService.EventType[] ReturnEventTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnEventTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnEventTypesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.EventType[]> ReturnEventTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnUserTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnUserTypesResponse")]
        TimetablingClientApplication.TimetablingService.UserType[] ReturnUserTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnUserTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnUserTypesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.UserType[]> ReturnUserTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomTypesResponse")]
        TimetablingClientApplication.TimetablingService.RoomType[] ReturnRoomTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomTypesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.RoomType[]> ReturnRoomTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildings", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingsResponse")]
        TimetablingClientApplication.TimetablingService.Building[] ReturnBuildings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildings", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingsResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Building[]> ReturnBuildingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourses", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCoursesResponse")]
        TimetablingClientApplication.TimetablingService.Course[] ReturnCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourses", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCoursesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Course[]> ReturnCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourseModules", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCourseModulesResponse")]
        TimetablingClientApplication.TimetablingService.Module[] ReturnCourseModules(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourseModules", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCourseModulesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Module[]> ReturnCourseModulesAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildingIdFromBuildingName", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingIdFromBuildingNameResponse")]
        int ReturnBuildingIdFromBuildingName(string buildingName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildingIdFromBuildingName", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingIdFromBuildingNameResponse")]
        System.Threading.Tasks.Task<int> ReturnBuildingIdFromBuildingNameAsync(string buildingName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourseIdFromCourseName", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCourseIdFromCourseNameResponse")]
        int ReturnCourseIdFromCourseName(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnCourseIdFromCourseName", ReplyAction="http://tempuri.org/ITimetablingService/ReturnCourseIdFromCourseNameResponse")]
        System.Threading.Tasks.Task<int> ReturnCourseIdFromCourseNameAsync(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomId", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomIdResponse")]
        int ReturnRoomId(int buildingId, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomId", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomIdResponse")]
        System.Threading.Tasks.Task<int> ReturnRoomIdAsync(int buildingId, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildingRooms", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingRoomsResponse")]
        TimetablingClientApplication.TimetablingService.Room[] ReturnBuildingRooms(int buildingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnBuildingRooms", ReplyAction="http://tempuri.org/ITimetablingService/ReturnBuildingRoomsResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Room[]> ReturnBuildingRoomsAsync(int buildingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomBuilding", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomBuildingResponse")]
        int ReturnRoomBuilding(int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomBuilding", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomBuildingResponse")]
        System.Threading.Tasks.Task<int> ReturnRoomBuildingAsync(int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomEventsResponse")]
        TimetablingClientApplication.TimetablingService.Event[] ReturnRoomEvents(int RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRoomEvents", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRoomEventsResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnRoomEventsAsync(int RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnTimes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnTimesResponse")]
        TimetablingClientApplication.TimetablingService.Time[] ReturnTimes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnTimes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnTimesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Time[]> ReturnTimesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRepeatTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRepeatTypesResponse")]
        TimetablingClientApplication.TimetablingService.RepeatType[] ReturnRepeatTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/ReturnRepeatTypes", ReplyAction="http://tempuri.org/ITimetablingService/ReturnRepeatTypesResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.RepeatType[]> ReturnRepeatTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewBuilding", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewBuildingResponse")]
        int CreateNewBuilding(string buildingName, int buildingNumber, string addressLine1, string addressLine2, string postCode, string buildingCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewBuilding", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewBuildingResponse")]
        System.Threading.Tasks.Task<int> CreateNewBuildingAsync(string buildingName, int buildingNumber, string addressLine1, string addressLine2, string postCode, string buildingCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRoom", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRoomResponse")]
        int CreateNewRoom(int buildingId, string roomName, string roomDescription, int roomTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRoom", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRoomResponse")]
        System.Threading.Tasks.Task<int> CreateNewRoomAsync(int buildingId, string roomName, string roomDescription, int roomTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRoomType", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRoomTypeResponse")]
        int CreateNewRoomType(string roomTypeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRoomType", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRoomTypeResponse")]
        System.Threading.Tasks.Task<int> CreateNewRoomTypeAsync(string roomTypeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRepeat", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRepeatResponse")]
        int CreateNewRepeat(string repeatTypeName, string repeatTypeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateNewRepeat", ReplyAction="http://tempuri.org/ITimetablingService/CreateNewRepeatResponse")]
        System.Threading.Tasks.Task<int> CreateNewRepeatAsync(string repeatTypeName, string repeatTypeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateSetting", ReplyAction="http://tempuri.org/ITimetablingService/CreateSettingResponse")]
        int CreateSetting(string settingName, string settingDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/CreateSetting", ReplyAction="http://tempuri.org/ITimetablingService/CreateSettingResponse")]
        System.Threading.Tasks.Task<int> CreateSettingAsync(string settingName, string settingDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/SearchFunction", ReplyAction="http://tempuri.org/ITimetablingService/SearchFunctionResponse")]
        TimetablingClientApplication.TimetablingService.Event[] SearchFunction(string appliedFilter, string searchItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimetablingService/SearchFunction", ReplyAction="http://tempuri.org/ITimetablingService/SearchFunctionResponse")]
        System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> SearchFunctionAsync(string appliedFilter, string searchItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimetablingServiceChannel : TimetablingClientApplication.TimetablingService.ITimetablingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimetablingServiceClient : System.ServiceModel.ClientBase<TimetablingClientApplication.TimetablingService.ITimetablingService>, TimetablingClientApplication.TimetablingService.ITimetablingService {
        
        public TimetablingServiceClient() {
        }
        
        public TimetablingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimetablingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimetablingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimetablingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Check_Email_Not_Exist(string email) {
            return base.Channel.Check_Email_Not_Exist(email);
        }
        
        public System.Threading.Tasks.Task<bool> Check_Email_Not_ExistAsync(string email) {
            return base.Channel.Check_Email_Not_ExistAsync(email);
        }
        
        public bool Register_User(TimetablingClientApplication.TimetablingService.User newUser) {
            return base.Channel.Register_User(newUser);
        }
        
        public System.Threading.Tasks.Task<bool> Register_UserAsync(TimetablingClientApplication.TimetablingService.User newUser) {
            return base.Channel.Register_UserAsync(newUser);
        }
        
        public int Login(string userName, string userPassword) {
            return base.Channel.Login(userName, userPassword);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string userName, string userPassword) {
            return base.Channel.LoginAsync(userName, userPassword);
        }
        
        public int CreateEvent(string eventTitle, int userId, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName) {
            return base.Channel.CreateEvent(eventTitle, userId, eventDescription, eventType, repeatType, eventDuration, startDate, eventTime, roomName, courseName, moduleName);
        }
        
        public System.Threading.Tasks.Task<int> CreateEventAsync(string eventTitle, int userId, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName) {
            return base.Channel.CreateEventAsync(eventTitle, userId, eventDescription, eventType, repeatType, eventDuration, startDate, eventTime, roomName, courseName, moduleName);
        }
        
        public bool EditEvent(int editedEventId, int userId, string eventTitle, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName) {
            return base.Channel.EditEvent(editedEventId, userId, eventTitle, eventDescription, eventType, repeatType, eventDuration, startDate, eventTime, roomName, courseName, moduleName);
        }
        
        public System.Threading.Tasks.Task<bool> EditEventAsync(int editedEventId, int userId, string eventTitle, string eventDescription, string eventType, string repeatType, int eventDuration, System.DateTime startDate, string eventTime, string roomName, string courseName, string moduleName) {
            return base.Channel.EditEventAsync(editedEventId, userId, eventTitle, eventDescription, eventType, repeatType, eventDuration, startDate, eventTime, roomName, courseName, moduleName);
        }
        
        public bool DeleteEvent(int eventId) {
            return base.Channel.DeleteEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventId) {
            return base.Channel.DeleteEventAsync(eventId);
        }
        
        public TimetablingClientApplication.TimetablingService.Event[] ReturnWeeksEvents(System.DateTime weekBeginning, int roomId) {
            return base.Channel.ReturnWeeksEvents(weekBeginning, roomId);
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnWeeksEventsAsync(System.DateTime weekBeginning, int roomId) {
            return base.Channel.ReturnWeeksEventsAsync(weekBeginning, roomId);
        }
        
        public TimetablingClientApplication.TimetablingService.Event[] ReturnEvents() {
            return base.Channel.ReturnEvents();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnEventsAsync() {
            return base.Channel.ReturnEventsAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.EventType[] ReturnEventTypes() {
            return base.Channel.ReturnEventTypes();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.EventType[]> ReturnEventTypesAsync() {
            return base.Channel.ReturnEventTypesAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.UserType[] ReturnUserTypes() {
            return base.Channel.ReturnUserTypes();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.UserType[]> ReturnUserTypesAsync() {
            return base.Channel.ReturnUserTypesAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.RoomType[] ReturnRoomTypes() {
            return base.Channel.ReturnRoomTypes();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.RoomType[]> ReturnRoomTypesAsync() {
            return base.Channel.ReturnRoomTypesAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.Building[] ReturnBuildings() {
            return base.Channel.ReturnBuildings();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Building[]> ReturnBuildingsAsync() {
            return base.Channel.ReturnBuildingsAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.Course[] ReturnCourses() {
            return base.Channel.ReturnCourses();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Course[]> ReturnCoursesAsync() {
            return base.Channel.ReturnCoursesAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.Module[] ReturnCourseModules(int courseId) {
            return base.Channel.ReturnCourseModules(courseId);
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Module[]> ReturnCourseModulesAsync(int courseId) {
            return base.Channel.ReturnCourseModulesAsync(courseId);
        }
        
        public int ReturnBuildingIdFromBuildingName(string buildingName) {
            return base.Channel.ReturnBuildingIdFromBuildingName(buildingName);
        }
        
        public System.Threading.Tasks.Task<int> ReturnBuildingIdFromBuildingNameAsync(string buildingName) {
            return base.Channel.ReturnBuildingIdFromBuildingNameAsync(buildingName);
        }
        
        public int ReturnCourseIdFromCourseName(string courseName) {
            return base.Channel.ReturnCourseIdFromCourseName(courseName);
        }
        
        public System.Threading.Tasks.Task<int> ReturnCourseIdFromCourseNameAsync(string courseName) {
            return base.Channel.ReturnCourseIdFromCourseNameAsync(courseName);
        }
        
        public int ReturnRoomId(int buildingId, string roomName) {
            return base.Channel.ReturnRoomId(buildingId, roomName);
        }
        
        public System.Threading.Tasks.Task<int> ReturnRoomIdAsync(int buildingId, string roomName) {
            return base.Channel.ReturnRoomIdAsync(buildingId, roomName);
        }
        
        public TimetablingClientApplication.TimetablingService.Room[] ReturnBuildingRooms(int buildingId) {
            return base.Channel.ReturnBuildingRooms(buildingId);
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Room[]> ReturnBuildingRoomsAsync(int buildingId) {
            return base.Channel.ReturnBuildingRoomsAsync(buildingId);
        }
        
        public int ReturnRoomBuilding(int roomId) {
            return base.Channel.ReturnRoomBuilding(roomId);
        }
        
        public System.Threading.Tasks.Task<int> ReturnRoomBuildingAsync(int roomId) {
            return base.Channel.ReturnRoomBuildingAsync(roomId);
        }
        
        public TimetablingClientApplication.TimetablingService.Event[] ReturnRoomEvents(int RoomName) {
            return base.Channel.ReturnRoomEvents(RoomName);
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> ReturnRoomEventsAsync(int RoomName) {
            return base.Channel.ReturnRoomEventsAsync(RoomName);
        }
        
        public TimetablingClientApplication.TimetablingService.Time[] ReturnTimes() {
            return base.Channel.ReturnTimes();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Time[]> ReturnTimesAsync() {
            return base.Channel.ReturnTimesAsync();
        }
        
        public TimetablingClientApplication.TimetablingService.RepeatType[] ReturnRepeatTypes() {
            return base.Channel.ReturnRepeatTypes();
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.RepeatType[]> ReturnRepeatTypesAsync() {
            return base.Channel.ReturnRepeatTypesAsync();
        }
        
        public int CreateNewBuilding(string buildingName, int buildingNumber, string addressLine1, string addressLine2, string postCode, string buildingCity) {
            return base.Channel.CreateNewBuilding(buildingName, buildingNumber, addressLine1, addressLine2, postCode, buildingCity);
        }
        
        public System.Threading.Tasks.Task<int> CreateNewBuildingAsync(string buildingName, int buildingNumber, string addressLine1, string addressLine2, string postCode, string buildingCity) {
            return base.Channel.CreateNewBuildingAsync(buildingName, buildingNumber, addressLine1, addressLine2, postCode, buildingCity);
        }
        
        public int CreateNewRoom(int buildingId, string roomName, string roomDescription, int roomTypeId) {
            return base.Channel.CreateNewRoom(buildingId, roomName, roomDescription, roomTypeId);
        }
        
        public System.Threading.Tasks.Task<int> CreateNewRoomAsync(int buildingId, string roomName, string roomDescription, int roomTypeId) {
            return base.Channel.CreateNewRoomAsync(buildingId, roomName, roomDescription, roomTypeId);
        }
        
        public int CreateNewRoomType(string roomTypeDescription) {
            return base.Channel.CreateNewRoomType(roomTypeDescription);
        }
        
        public System.Threading.Tasks.Task<int> CreateNewRoomTypeAsync(string roomTypeDescription) {
            return base.Channel.CreateNewRoomTypeAsync(roomTypeDescription);
        }
        
        public int CreateNewRepeat(string repeatTypeName, string repeatTypeDescription) {
            return base.Channel.CreateNewRepeat(repeatTypeName, repeatTypeDescription);
        }
        
        public System.Threading.Tasks.Task<int> CreateNewRepeatAsync(string repeatTypeName, string repeatTypeDescription) {
            return base.Channel.CreateNewRepeatAsync(repeatTypeName, repeatTypeDescription);
        }
        
        public int CreateSetting(string settingName, string settingDescription) {
            return base.Channel.CreateSetting(settingName, settingDescription);
        }
        
        public System.Threading.Tasks.Task<int> CreateSettingAsync(string settingName, string settingDescription) {
            return base.Channel.CreateSettingAsync(settingName, settingDescription);
        }
        
        public TimetablingClientApplication.TimetablingService.Event[] SearchFunction(string appliedFilter, string searchItem) {
            return base.Channel.SearchFunction(appliedFilter, searchItem);
        }
        
        public System.Threading.Tasks.Task<TimetablingClientApplication.TimetablingService.Event[]> SearchFunctionAsync(string appliedFilter, string searchItem) {
            return base.Channel.SearchFunctionAsync(appliedFilter, searchItem);
        }
    }
}
